// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Milpa",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Milpa",
            targets: ["AppModule"],
            bundleIdentifier: "com.isaac.VirtualGarden",
            teamIdentifier: "22U6F5C7AF",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Used to scan real plants to extract color and height data")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources"),
                .process("Data")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)